Update checkov.yaml

diff --git a/.github/workflows/checkov.yaml b/.github/workflows/checkov.yaml
--- a/.github/workflows/checkov.yaml
+++ b/.github/workflows/checkov.yaml
@@ -5,45 +5,41 @@ on:
     branches:
       - '*'
 
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  build:
-
+  # This workflow contains a single job called "scan"
+  scan:
+    permissions:
+      contents: read # for actions/checkout to fetch code
+      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+      
+    # The type of runner that the job will run on
     runs-on: ubuntu-latest
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python 3.8
-        uses: actions/setup-python@v1
+      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
+      - uses: actions/checkout@v3
+
+      - name: Checkov GitHub Action
+        uses: bridgecrewio/checkov-action@v12
         with:
-          python-version: 3.8
-      - name: Install checkov
-        run: pip install checkov
-
-      - name: Run Checkov and capture output
-        id: checkov
-        run: |
-          echo "running checkov on directory: staging/ap-southasia-1/staging"
-          checkov -d staging/ap-southasia-1/staging --output sarif --framework terraform > ${{ github.workspace }}/results.sarif
-          cat ${{ github.workspace }}/results.sarif
-          echo "::set-output name=checkov-output::$(cat ${{ github.workspace }}/results.sarif)"
-
-      - name: Adjust file permissions
-        run: |
-          chmod 644 ${{ github.workspace }}/results.sarif
-
-      - name: Extract specific results
-        id: extract-results
-        run: |
-          grep "Check:" ${{ github.workspace }}/results.sarif > ${{ github.workspace }}/filtered-results.txt
-          echo "::set-output name=filtered-results::$(cat ${{ github.workspace }}/filtered-results.txt)"
-
-      - name: Comment on pull request
-        uses: actions/github-script@v4
+          # This will add both a CLI output to the console and create a results.sarif file
+          output_format: cli,sarif
+          output_file_path: console,results.sarif
+        
+      - name: Upload SARIF file
+        uses: github/codeql-action/upload-sarif@v2
+        
+        # Results are generated only on a success or failure
+        # this is required since GitHub by default won't run the next step
+        # when the previous one has failed. Security checks that do not pass will 'fail'.
+        # An alternative is to add `continue-on-error: true` to the previous step
+        # Or 'soft_fail: true' to checkov.
+        if: success() || failure()
         with:
-          script: |
-            const output = `Checkov scan results:\n\n${process.env.filtered_results}`;
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            });
+          sarif_file: results.sarif
